name: Test Endpoint

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name myapp_container myapp

      - name: Wait for the container to be ready
        run: sleep 10

      - name: Test endpoint with curl
        run: curl http://localhost:8080/api/v1/cryptos