name: Test Endpoint

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Docker compose up
        run: docker compose up -d

      - name: Wait for the container to be ready
        run: sleep 10

      - name: list containers
        run: docker ps

      - name: Test endpoint with curl
        run: curl http://localhost:8080/api/v1/cryptos