name: Building test
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: go-1.23

    steps:
      - uses: actions/checkout@v4


      - name: Setup go
        run: |
            go version
            go env
            go get -u github.com/golang/dep/cmd/dep
            go get -u golang.org/x/lint/golint
            go get -u github.com/golang/protobuf/protoc-gen-go
            go get -u github.com/golang/protobuf/proto

      - name: test
        run: make test

      - name: build
        run: make build
